djangoProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^papers/', include('papers.urls')),
    url(r'^admin/', admin.site.urls),
]

papers/urls.py
from django.conf.urls import url

from . import views
from django.urls import path

app_name = 'papers'

urlpatterns = [
    path('index', views.index, name="index"),
    path('', views.show, name="show"),
    path('content/<int:pk>/', views.detail, name='detail'),
    path('<str:keyword>=<str:value>/', views.filter_by_keyword, name='filter_by_keyword'),
    path('search/<str:keywords>', views.filter_by_keywords, name='filter_by_keywords')
]

papers/models.py
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField("研究主题", max_length=10, primary_key=True, blank=False)

    class Meta:
        verbose_name = '主题'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField("论文标签", max_length=10, primary_key=True, blank=False)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Researcher(models.Model):
    name = models.CharField("姓名", max_length=10, primary_key=True, blank=False)
    # topic = models.CharField("研究主题", max_length=50, blank=False)
    topic = models.ForeignKey(Topic, verbose_name="研究主题",
                                   null=True,
                                   on_delete=models.SET_NULL, blank=False)

    class Meta:
        verbose_name = '上传者'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Paper(models.Model):
    title = models.CharField("论文题目", max_length=200, blank=False)
    researcher = models.ForeignKey(Researcher, verbose_name="上传人",
                                   null=True,
                                   on_delete=models.SET_NULL, blank=False)
    # tag = models.CharField("具体标签", max_length=50, blank=False)
    tag = models.ManyToManyField(Tag, verbose_name="论文标签", blank=False)
    review = models.TextField("论文总结", blank=False)

    class Meta:
        verbose_name = '论文'
        verbose_name_plural = verbose_name
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('papers:detail', kwargs={'pk': self.pk})

papers/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .models import *
import markdown2
import re
from django.db.models.aggregates import Count


def clean_review(original_review):
    new_review = original_review.replace('#', '')
    new_review = new_review.replace('-', '')
    new_review = new_review.replace('*', '')
    return new_review


def change_formula(matched):
    formula = matched.group(0)
    formula = formula.replace('_', ' _')
    return '\n<p>' + formula + '</p>\n'


def index(request):
    topic_list = Topic.objects.all()
    tag_list = Tag.objects.annotate(paper_num=Count('paper')).order_by('-paper_num')
    return render(request, 'papers/index.html', context={'topic_list': topic_list, 'tag_list': tag_list})


def show(request):
    # 过滤数据，获取满足条件的paper
    # 注意filter只能写=，不能写不等于
    paper_list = Paper.objects.all()
    tag_list = Tag.objects.annotate(paper_num=Count('paper')).order_by('-paper_num')
    for paper in paper_list:
        review_length = len(paper.review)
        paper.small_review = clean_review(paper.review[0:min(review_length, 200)])
    return render(request, 'papers/show.html',
                  context={'paper_list': paper_list, 'tag_list': tag_list})


def detail(request, pk):
    # 不存在时返回404错误
    paper = get_object_or_404(Paper, pk=pk)
    # 判断是否已经登录
    if request.user.is_authenticated:
        # 上传用户或管理员可以见到编辑界面
        paper.if_updater = (paper.researcher == Researcher.objects.get(name=request.user) or request.user.is_superuser)
    else:
        paper.if_updater = True
    paper.review = markdown2.markdown(re.sub(r'\$\$(.+?)\$\$', change_formula, paper.review))
    return render(request, 'papers/detail.html', context={'paper': paper})


def filter_by_keyword(request, keyword, value):
    try:
        if keyword == '上传者':
            paper_list = Paper.objects.filter(researcher=Researcher.objects.get(name=value))
        elif keyword == '小组':
            print(Topic.objects.get(name=value))
            researchers = Researcher.objects.filter(topic=Topic(name=value))
            print(researchers)
            paper_list = []
            for researcher in researchers:
                paper_list += Paper.objects.filter(researcher=Researcher.objects.get(name=researcher.name))
        elif keyword == '标签':
            paper_list = Paper.objects.filter(tag=Tag.objects.get(name=value))
        else:
            return show(request)
        tag_list = Tag.objects.annotate(paper_num=Count('paper')).order_by('-paper_num')
        for paper in paper_list:
            review_length = len(paper.review)
            paper.small_review = clean_review(paper.review[0:min(review_length, 200)])
        return render(request, 'papers/show.html',
                      context={'paper_list': paper_list, 'tag_list': tag_list})
    except:
        return show(request)


def filter_by_keywords(request, keywords):
    try:
        if '&' in keywords:
            condition_key = '&'
        elif '|' in keywords:
            condition_key = '|'
        else:
            return show(request)
        select_tag_list = keywords.split(condition_key)
        if select_tag_list[-1] == '':
            select_tag_list = select_tag_list[:-1]
        if condition_key == '&':
            paper_list = Paper.objects.all()
            for select_tag in select_tag_list:
                paper_list = paper_list.filter(tag=Tag(name=select_tag))
        else:
            q = Q()
            q.connector = 'OR'
            for select_tag in select_tag_list:
                q.children.append(('tag', Tag(name=select_tag)))
            paper_list = Paper.objects.filter(q).distinct()
            print(paper_list, q)
        tag_list = Tag.objects.annotate(paper_num=Count('paper')).order_by('-paper_num')
        for paper in paper_list:
            review_length = len(paper.review)
            paper.small_review = clean_review(paper.review[0:min(review_length, 200)])
        return render(request, 'papers/show.html',
                      context={'paper_list': paper_list, 'tag_list': tag_list,
                               'select_tag_list': select_tag_list})
    except:
        return show(request)

templates/base.html
{% load static %}
{#{% load mathjax %}#}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}
    {% endblock title %}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'papers/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'papers/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'papers/css/buttons.css' %}">

    <!-- js -->
    <script src="{% static 'papers/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'papers/js/modernizr.custom.js' %}"></script>
    {#    {% mathjax_scripts %}#}
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
    showProcessingMessages: false, //关闭js加载过程信息
    messageStyle: "none", //不显示信息
    extensions: ["tex2jax.js"],
    jax: ["input/TeX", "output/HTML-CSS"],
    tex2jax: {
        inlineMath:  [['$', '$']], //行内公式选择$
        displayMath: [ ["$$","$$"] ], //段内公式选择$$
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre','code','a'], //避开某些标签
        ignoreClass:"comment-content" //避开含该Class的标签
    },
    "HTML-CSS": {
        availableFonts: ["STIX","TeX"], //可选字体
        showMathMenu: true //关闭右击菜单显示
    }
    });
    MathJax.Hub.Queue(["Typeset",MathJax.Hub]);

    </script>
    <script src="//cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <link rel="dns-prefetch" href="//cdn.mathjax.org" />
</head>

<body>
<div class="container paper">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1>{% block ttitle %}
                {% endblock ttitle %}</h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href={% url "papers:index" %} data-hover="首页">首页</a></li>
                            {% block button1 %}{% endblock button1 %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>


<div class="content-body">
    {% block main %}
    {% endblock main %}
</div>


<script src="{% static 'papers/js/script.js' %}"></script>

</body>
</html>

templates/papers/detail.html
{% extends 'base.html' %}

{% block title %}
    论文详情
{% endblock title %}

{% block ttitle %}
    论文详情
{% endblock ttitle %}

{% block button1 %}
    <li class="cl-effect-11"><a href="{% url "papers:show" %}" data-hover="论文列表">论文列表</a></li>
    <li class="cl-effect-11"><a href="{% url "admin:index" %}papers/paper/add/" data-hover="上传">上传</a></li>
    {% if paper.if_updater %}
        <li class="cl-effect-11"><a href="{% url "admin:index" %}papers/paper/{{ paper.pk }}/change" data-hover="编辑">编辑</a></li>
    {% endif %}
{% endblock button1 %}

{% block main %}
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                <article class="post post">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            {{ paper.title }}
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category">{{ paper.researcher.topic.name }}</span>
                            <span class="post-author">{{ paper.researcher.name }}</span>
                        </div>
                        <div class="widget widget-tag-cloud show-tag">
                            {% for t in paper.tag.all %}
                                <ul>
                                    <li>
                                        {{ t.name }}
                                    </li>
                                </ul>
                            {% endfor %}
                        </div>
                    </header>
                    <div class="big-content clearfix">
                        {{ paper.review | safe }}
                    </div>
                </article>
            </main>
        </div>
    </div>
{% endblock main %}

templates/papers/index.html
{% extends 'base.html' %}

{% block title %}
    首页
{% endblock title %}

{% block ttitle %}
    首页
{% endblock ttitle %}

{% block button1 %}
    <li class="cl-effect-11"><a href="{% url "papers:show" %}" data-hover="论文列表">论文列表</a></li>
    <li class="cl-effect-11"><a href="{% url "admin:index" %}papers/paper/add" data-hover="上传">上传</a></li>
{% endblock button1 %}

{% block main %}
    <div class="container paper">
        <div class="row">
            <main class="col-md-12">
                {% for topic in topic_list %}
                    <h1 class="entry-title">
                        <a href={% url 'papers:filter_by_keyword' '小组' topic.name %}>{{ topic.name }}小组</a>
                    </h1>
                    <div class="widget widget-tag-cloud">
                        {% for researcher in topic.researcher_set.all %}
                            <ul>
                                <li>
                                    <a href={% url 'papers:filter_by_keyword' '上传者' researcher.name %}>{{ researcher.name }}</a>
                                </li>
                            </ul>
                        {% endfor %}
                    </div>
                {% endfor %}
                <div class="widget widget-tag-cloud  select-area">
                    <h3 class="widget-title">条件筛选</h3>
                    {% for tag in tag_list %}
                        <ul>
                            {% if tag.name in select_tag_list %}
                                <li class="after-select-li">
                                    <span>{{ tag.name }}</span> {{ tag.paper_num }}篇
                                </li>
                            {% else %}
                                {% if tag.paper_num > 0 %}
                                    <li class="before-select-li">
                                        <span>{{ tag.name }}</span> {{ tag.paper_num }}篇
                                    </li>
                                {% else %}
                                    <li class="no-select-li">
                                        <span>{{ tag.name }}</span> {{ tag.paper_num }}篇
                                    </li>
                                {% endif %}
                            {% endif %}
                        </ul>
                    {% endfor %}
                </div>
                <div class="button_area">
                    <button class="and_button condition_button green button big_button">与查询</button>
                    <button class="or_button condition_button green button big_button">或查询</button>
                    <button class="empty_button button big_button">清空</button>
                </div>
            </main>
        </div>
    </div>
{% endblock main %}

templates/papers/show.html
{% extends 'base.html' %}

{% block title %}
    论文列表
{% endblock title %}

{% block ttitle %}
    论文列表
{% endblock ttitle %}

{% block button1 %}
    <li class="cl-effect-11"><a href="{% url "papers:show" %}" data-hover="论文列表">论文列表</a></li>
    <li class="cl-effect-11"><a href="{% url "admin:index" %}papers/paper/add/" data-hover="上传">上传</a></li>
{% endblock button1 %}

{% block main %}
    <div class="container paper">
        <div class="row">
            <main class="col-md-9">
                {% for paper in paper_list %}
                    <article class="post">
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{{ paper.get_absolute_url }}">{{ paper.title }}</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="post-category"><a
                                        href={% url 'papers:filter_by_keyword' '小组' paper.researcher.topic.name %}>{{ paper.researcher.topic.name }}</a></span>
                                <span class="post-author"><a
                                        href={% url 'papers:filter_by_keyword' '上传者' paper.researcher.name %}>{{ paper.researcher.name }}</a></span>
                            </div>
                            <div class="widget widget-tag-cloud show-tag">
                                {% for t in paper.tag.all %}
                                    <ul>
                                        <li>
                                            <a href={% url 'papers:filter_by_keyword' '标签' t.name %}>
                                                {{ t.name }}
                                            </a>
                                        </li>
                                    </ul>
                                {% endfor %}
                            </div>
                        </header>
                        <div class="small-content clearfix">
                            <p>{{ paper.small_review }}</p>
                        </div>
                    </article>
                {% empty %}
                    <div class="no-post">不存在满足条件的论文！</div>
                {% endfor %}
            </main>
            <aside class="col-md-3">
                <div class="widget widget-tag-cloud  select-area">
                    <h3 class="widget-title">条件筛选</h3>
                    {% for tag in tag_list %}
                        <ul>
                            {% if tag.name in select_tag_list %}
                                <li class="after-select-li">
                                    <span>{{ tag.name }}</span> {{ tag.paper_num }}篇
                                </li>
                            {% else %}
                                {% if tag.paper_num > 0 %}
                                    <li class="before-select-li">
                                        <span>{{ tag.name }}</span> {{ tag.paper_num }}篇
                                    </li>
                                {% else %}
                                    <li class="no-select-li">
                                        <span>{{ tag.name }}</span> {{ tag.paper_num }}篇
                                    </li>
                                {% endif %}
                            {% endif %}
                        </ul>
                    {% endfor %}
                </div>
                <div class="button_area">
                    <button class="and_button condition_button button green">与查询</button>
                    <button class="or_button condition_button button green">或查询</button>
                    <button class="empty_button button">清空</button>
                </div>
            </aside>
        </div>
    </div>
{% endblock main %}